version: "3.8"

services:
  grpc-server:
    build:
      context: .
      dockerfile: cache/Dockerfile
    container_name: grpc-server
    ports:
      - "50051:50051"

  api-gateway:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - grpc-server
    environment:
      - GRPC_TARGET=grpc-server:50051